### ISSUE TITLE
Allow searching and display of modules not offered in the current AY

### ISSUE THREAD

**Issue by taneliang** [nusmodifications/nusmods#1775]
[NUS Bulletin's Search Modules page](http://www.nus.edu.sg/nusbulletin/search-modules/) will be removed in July, and NUSMods is to take over this functionality for the university.

![image](https://user-images.githubusercontent.com/12784593/57903531-01fdf880-78a1-11e9-8711-0a42d82f40fd.png)

However, NUSMods currently does not show modules which are not offered in the system, an essential feature. We accomplish this by ignoring all modules which do not have timetables. This was done because there was no need to show non-offered mods. However RO has since told us that:

> The reason why we may need a comprehensive listing of active modules in NUSMods (including those that haven’t been timetabled) is because students may wish to e.g. map a module they have taken while on SEP back to NUS. 

### TODO

- [ ] Modify scraper to process all mods, even if they're not offered in the AY
- [ ] Modify website to search through all 11+k modules. This will require an overhaul of the module search page as the current offline search is not scalable for longer - it currently downloads 5+MB of data (for ~5.5k mods) when the module page is loaded, and the new combined offered+non-offered mods list is over 10MB in size. Also, searching through more modules will require more computational power that weaker devices will not be able to support.

**Comment by taneliang** [comment]
New module search bugs introduced in #1791 that have to be fixed before deploying

- [ ] Pager is too wide on mobile devices and tablets, especially after navigating a few pages.
- [ ] Pager is not styled correctly in dark mode.
- [ ] API error looks bad as it does not take up the whole screen.
    ![localhost_8080_modules_level 0 =8000 mcs 0 =9](https://user-images.githubusercontent.com/12784593/58023350-29272500-7b42-11e9-98db-ab0f422b103e.png)
- [ ] `<X> modules found` text does not display the current page or the current range of displayed mods, which can be confusing.
- [ ] No results found for empty search string is bad. Demo: http://localhost:8080/modules?level[0]=8000&mcs[0]=9 
    ![image](https://user-images.githubusercontent.com/12784593/58022874-047e7d80-7b41-11e9-88ed-f42710c960e1.png)
- [ ] Only show mods offered this AY by default
- [ ] Mods should be sorted by module code if there are no selected filters and no search query

**Comment by taneliang** [comment]
New module search bugs caused by data changes in #1776 

- [ ] Fix display of non-offered mods in the module list (together with the Elasticsearch module search overhaul)
![image](https://user-images.githubusercontent.com/12784593/57903050-d11cc400-789e-11e9-9d4c-6a87b7219629.png)
- [ ] Fix non-functional "Add to" button in the module page 
![image](https://user-images.githubusercontent.com/12784593/57903093-1a6d1380-789f-11e9-8426-760c066ebf1a.png)
- [ ] Add notice to module page to notify user that the module is not offered in the AY

**Comment by taneliang** [comment]
- [ ] Techdebt: default query string introduced in https://github.com/nusmodifications/nusmods/pull/1889 is a terrible solution and should be fixed.
