### ISSUE TITLE
Blockers for NUSMods R release 

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#464]
This is a meta issue tracking hard/soft blockers for v3 

### Hard blockers 

- General
  - [X] CORS bidding notification 
  - [X] Module select dropdown menu (#484) 

- Timetable page
  - [X] Multiple semester support - able to add module to and switch to timetables of other semesters 
  - [X] Exam time clash warning (https://github.com/nusmodifications/nusmods/issues/483)
  - [X] Timetable sharing
  - [X] v2 to v3 timetable migration (#507) 

- Module page
  - [X] Add to timetable button (#508) 
  - [X] Disqus reviews 

- Module finder 
  - [X] Semester, faculty and department filter (Semester filter is done with #491) 

#### v2 parity 

- [x] Venues page (partially done via #498, #526)  
- [x] Google Analytics 
- [x] Dark mode
- [x] Information correct as timestamp in footer (#586)

- Module page 
  - [x] CORS bidding stats 
  - [x] Prereq tree (#451) 

- Module finder 
  - [X] Module search 

#### New features 

- [X] Improve header 
- [x] Page actions via FAB (#510) 
- [x] Offline support via service worker (#539) 

#### v2 parity 

- [ ] Link to filters 
- [ ] Module code link tooltip 
- [x] Link shortener 

#### New features 

- [ ] Today page 
- [ ] GraphQL backend

**Comment by ZhangYiJiang** [comment]
Closing this since R has launched, so the issue doesn't make much sense anymore. Took the remaining items and turned them into individual issues.
