### ISSUE TITLE
GraphQL Roadmap

### ISSUE THREAD

**Issue by taneliang** [nusmodifications/nusmods#716]
Meta issue tracking all tasks we need to do to move to GraphQL.

### Infra and decisions

- [x] Monorepo (good to have but not essential)
- [ ] We need some way to run the server. `PM2`
- [ ] Do we want to run it on the same droplet or another droplet?
- [x] Do we want to use Docker? Will take about 10 min for @li-kai to set up. We can limit memory usage, and if we were extremely rich we could set up auto scaling.

### GraphQL server code

- [ ] Add school name to schema and queries
- [ ] Add query param to be able to filter data by semester
- [ ] Venue support (basically only the new location schema)

Keep in mind other schools' requirements while we're building this schema.

### Actual migration

- [ ] Install Apollo and Apollo GraphQL loaders
- [ ] Migrate venues client to GraphQL backend
- [ ] Migrate modules on client to GraphQL backend
- [ ] Finally migrate module search, which is the hardest problem.
- [ ] Rip out REST related code
