### ISSUE TITLE
Venue location enhancement roadmap

### ISSUE THREAD

**Issue by taneliang** [nusmodifications/nusmods#745]
This is a meta issue tracking the enhancement of the venues page with location data, and possibly bus routing data. Follows up on #654.

### API

- [ ] Finalize GraphQL API schema for enhanced venues
- [ ] Integrate the prototype [venue location data scraper](https://github.com/taneliang/NUSVenues) with existing venue scraper
- [ ] Find a way to store user inputs from the venue location feedback box (see below)
- [ ] Implement some sort of NUSMods venue/NUS room matcher override. Reasons:
    - NUS's fuzzy matcher can produce bad results, e.g. [LT10 is matched to a female toilet](https://github.com/taneliang/NUSVenues/blob/81a96585550b5a2ea1a3edd2a7f6a9d24bd7d42a/results/finalVenues.json#L366)
    - Some venue names are so dissimilar from their room codes that the fuzzy matcher can't match them
- [ ] Implement a custom location datasource, so that we can use use user-provided locations. These locations won't need to be matched.

### Client

- [ ] Display room names and actual NUS room codes
- [ ] Display map in venue detail view
- [ ] Beta notice and feedback box to allow users to correct wrong venue names/room codes/locations
- [ ] A way to select venues on a map instead of scrolling through a list. We need a way to handle venues with no GPS coords in this case.

### Bus feature

This concept has to be further baked before implementation. It may even be better implemented as a separate mobile app instead of integrating it with NUSMods proper. Bus routes and timings can be obtained from a [Comfort API](https://nextbus.comfortdelgro.com.sg).

- [ ] Nearest bus stop feature
- [ ] Bus routing between venues. https://gothere.sg might be useful
- [ ] Directions to the next class (perfect for a Today view)
